# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/HerbariaOCR',
                'doc_host': 'https://BU-Spark.github.io',
                'git_url': 'https://github.com/BU-Spark/HerbariaOCR',
                'lib_path': 'HerbariaOCR'},
  'syms': {'HerbariaOCR.core': {'HerbariaOCR.core.foo': ('core.html#foo', 'HerbariaOCR/core.py')}}}
